theme: jekyll-theme-cayman
markdown: GFM
title: Block malicious traffic with a tomato router
description: This page contains instruction how you can configure your FreshTomato router to block incoming requests malicious from source like tor, shodan, stretchoid and binary-edge.